name: Auto-add to project board

on:
  issues:
    types: [opened, transferred]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/singi-labs/projects/2
          github-token: ${{ secrets.PROJECT_TOKEN }}
